# Permalinks
permalink: /:year-:month/:slug/

# Asset compiling
sass:
  style: :compressed

# Site settings
title: Toronto Mesh
email: hello@tomesh.net
description: We are building a mesh network in Toronto.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tomesh.net" # the base hostname & protocol for your site
github_username: tomeshnet

# Collections
collections:
  announcements:
    output: false

# Build settings
markdown: kramdown
future: true # for events set in the future to show up

# Excluded folders
exclude: [scripts]

# Events pagination
paginate: 6
paginate_path: "events/page:num"

# Jekyll gems
gems: [jekyll-paginate]
