# Permalinks
permalink: /:year-:month-:day/:slug/

# Asset compiling
sass:
  style: :compressed

# Site settings
title: Toronto Mesh
email: hello@tomesh.net
description: We are building a mesh network in Toronto.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tomesh.net" # the base hostname & protocol for your site
github_username: tomeshnet
twitter_username: tomeshnet

# Collections
collections:
  timeline:
    output: false
  announcements:
    output: false

# Build settings
markdown: kramdown
future: true # for events set in the future to show up

# Excluded folders
exclude: [Gemfile, Gemfile.lock, scripts, vendor]

# Include folders
include: [.well-known]

# Keep files (Dat files)
keep_files: [.dat]

# Events pagination
paginate: 8
paginate_path: "events/page-:num"

# Jekyll gems
plugins: [jekyll-paginate]
